# Generated by Django 4.0.5 on 2022-06-22 09:56

import crab.models
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Kateqoriya adı')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slaq adı')),
            ],
            options={
                'verbose_name': 'Kateqoriya',
                'verbose_name_plural': 'Kateqoriya',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Şəhər adı')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Slaq adı')),
            ],
            options={
                'verbose_name': 'Şəhər',
                'verbose_name_plural': 'Şəhər',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Xətanın Yükləmə tarixi')),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Vakansiya adı')),
                ('company', models.CharField(max_length=250, verbose_name='İş verən şirkət')),
                ('description', models.TextField(verbose_name='Açıqlama')),
                ('salary', models.CharField(max_length=60, verbose_name='Maaş')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Yükləmə tarixi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crab.category', verbose_name='Kateqoriya')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crab.city', verbose_name='Şəhər')),
            ],
            options={
                'verbose_name': 'Vakansiya',
                'verbose_name_plural': 'Vakansiya',
                'ordering': ['-create_at'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_data', jsonfield.fields.JSONField(default=crab.models.default_urls)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crab.category', verbose_name='Kateqoriya')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crab.city', verbose_name='Şəhər')),
            ],
            options={
                'unique_together': {('city', 'category')},
            },
        ),
    ]
