# Generated by Django 4.0.5 on 2022-07-03 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crab', '0003_alter_error_create_at_alter_vacancy_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='create_at',
            field=models.DateField(auto_now_add=True, verbose_name='Xətanın tarixi'),
        ),
    ]
